[package]
name = "rust_api_mongodb"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
chrono = "0.4.42"
futures-util = "0.3.31"
tokio-stream = "0.1"
mongodb = "3.4.1"
serde = "1.0.228"
